PR : mainPage 프로필 부분  디자인 수정했습니다
mobi-projects/mobi-3rd-1-typescript pull request #121
Opened 2024-05-15 07:26 UTC by keeprok

## 🔥 Issues

- close #113 

<br/>
<br/>

## 🎯 작업 내용

- [publish : mainIcon추가및 사진 재배치](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/0be99970aecf257707504c9d0a4b0abedf4fffc3)
- profile의  header빈공간이 밋밋하다는의견이있어 
-  페이지의 MainIcon 추가 (detail 과 같이 출판사를 의미)
- 그전 배경의  회색빛이 어두워서 프로필의빈공간이 부각된다고 생각이들어 색을 조금더 가벼운색을 사용하였습니다 
-  프로필이 중점적으로 보일수있게 위치를 밑으로 조정했습니다 

![스크린샷 2024-05-15 오후 3 30 11](https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/140785214/4c7405a4-9bff-43ff-8d42-814bdc32d823)

-[publish : 반응형 사이즈 추가](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/f1bacfbd7d80a736d5cafe4842cf48898582f0ec)
- iponeXr사이즈로 했을경우 너무 아이콘이 커서  반응형추가했습니다

![스크린샷 2024-05-15 오후 4 13 54](https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/140785214/a2133e4e-14b1-474f-8677-8a8a5f3f5718)

<br/>
<br/>

## ✅ 체크 리스트

-   [ ] Main 브랜치 Pull 받기
-   [ ] Issue 번호 설정 확인
-   [ ] Label 확인
-   [ ] Assignees 설정 확인
-   [ ] Reviewers 설정 확인

<br/>
<br/>

-----

#### 🙏 꼭 리뷰 남겨주세요.!!
- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-05-15 07:47 UTC, snkchan requested changes
- 디자인을 수정해주셨는데 로고가 추가된것으로 여백을 채워서 문제점을 해결 하셧는데 이대로도 괜찮을까요??? 지금 디자인에 사용자가 별로라고 느꼇다는 피드백이 왔다면 배치를 바꾸거나 다른 참고자료를 좀 찾아봤을것 같아요. 
- [레퍼런스1](https://www.figma.com/design/W7OW2ANPsqNL4U7SWYyzBS/Profile-Edit-(Community)?node-id=0-1&t=ITwmejn9XoYg1Lgm-0)
- [레퍼런스2](https://www.figma.com/design/AsL3kq3zeo7NAXltUbzLjZ/Profile-page-Mobile-UI-(Community)?node-id=0-1&t=4rPf1LTCvT0s1OX4-0)
- [레퍼런스3](https://www.figma.com/design/T9qloOFb7WDRJR7n2q19Rq/User-Profile-Design-(Community)?node-id=101-2&t=RrD8JchSx3AyneMz-0)
- 이거말고도 더많은자료들이 있는데 현재 디자인과 비슷한 다른 참고자료를 찾아보시는 것도 방법 아닐까요?

2024-05-15 07:47 UTC, snkchan commented on src/pages/my/components/my.profile-image.tsx
> +            className=" h-[4.5rem] w-[4.5rem] rounded-full IPHON_XR:h-[3rem] IPHON_XR:w-[3rem]"
# Request Level


  - [x] "🚨 꼭 수정해주세요.!"


<!--
  - [x] "🚧 재고해주시길.."
-->

<!--
  - [x] "✅ LGTM"
-->

# Description
- 반응형을 적용해주셧는데 지금 
- <img width="238" alt="image" src="https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/144839872/a8ffdaa4-ec94-49d6-846f-e7a8faf073f6">
1번에 보시면 완전붙어있어서 이대로는 안될거 같아요. 모바일환경에서 공간이좁아서 logo배치가 애매하다면
2번에 위치한곳에 absolute를 사용하셔서 배치하는 것도 방법일 것 같고. 그 방법도 별로라면 로고를 차라리 안보이게처리하거나 하셔야할 것 같아요.
- 요청사항에 의해 수정을 해주셧는데 지금 반응형을 추가해주신것은 완성된 pr이다라고 볼수 없을 것 같아요... 서비스에서 저런 배치를 보신다면 어떻게 느끼실지 생각해보셧으면 좋겠습니다.
디자인이 저희 영역이 아니라고하지만 사용자에게 어떻게 보여질지를 생각해보는 것은 저희 영역이라고 생각이 되네요.

2024-05-15 08:29 UTC, TransparentDeveloper requested changes
🙄 tailwind 는 리뷰하기 너무 어렵네여;; 

고생하셨습니다.

2024-05-15 08:29 UTC, TransparentDeveloper commented on src/pages/my/components/my.profile-image.tsx
>  import { UserType } from "@/types"
영로쿤,, type 을 외부에서 가져올 경우, 나중에 지워야할 import 구문임을 tsc 에 알려줘야 한다하네요.!

수정 부탁합니다 :)

2024-05-16 06:03 UTC, keeprok commented on src/pages/my/components/my.profile-image.tsx
> +            className=" h-[4.5rem] w-[4.5rem] rounded-full IPHON_XR:h-[3rem] IPHON_XR:w-[3rem]"
[publish : 반응형 디자인 수정](https://github.com/mobi-projects/mobi-3rd-1-typescript/pull/121/commits/4e2be65cfc06a5d3d3b9460f3a3df78cf0d44906) 
- 로고가 주요한 기능 을 포함하고 있지는 않다고 생각이들어 반응형일때는 삭제를 조치하기로 하였습니다 
- 피드백을 받았을때 전반적인 디자인이 별로다라는 의견보다는header의 불필요한 크기에 관한 메세지가 많다보니 시선이 그쪽으로 간것같습니다 
- 그리고 다른 레퍼런스를 안본것은아니나 저희 mypage특성상 사진,닉네임 변경을 제외하고 는 기능적인 면(예를 들면 다른웹사이트에서 설정 ?) 보다는 정보를  시각적으로 보여주는 면이라는 생각이들었고 그점은 디테일 페이지와 유사하다 여서 다른 레퍼런스에 맞추는것보다는 책과 비슷하게 디자인을 잡아가는것이 좋다는 생각이 들엇습니다 그래서 중점적으로 들어온 배너에게 특색을 주자가 결론이 되었습니다

2024-05-16 06:08 UTC, keeprok commented on src/pages/my/components/my.profile-image.tsx
>  import { UserType } from "@/types"
[fix : tsc설정에맞춰서 수정,수정했습니다. 감사합니다 @](https://github.com/mobi-projects/mobi-3rd-1-typescript/pull/121/commits/be7b66420dcd0c2743b5483551033cbdd4fd4cfd)

2024-05-16 06:52 UTC, snkchan commented on src/pages/my/components/my.profile-image.tsx
> +            className=" h-[4.5rem] w-[4.5rem] rounded-full IPHON_XR:h-[3rem] IPHON_XR:w-[3rem]"
@keeprok 
그래서 수정후에는 어떻게 보여지는건지도 보여주실 수 있을까요?? 코드만봐서는 모르겠습니다!

2024-05-16 23:54 UTC, TransparentDeveloper approved these changes
고생하셨습니다.! 🙃

2024-05-17 11:09 UTC, keeprok commented on src/pages/my/components/my.profile-image.tsx
> +            className=" h-[4.5rem] w-[4.5rem] rounded-full IPHON_XR:h-[3rem] IPHON_XR:w-[3rem]"
<img width="343" alt="스크린샷 2024-05-17 오후 8 08 42" src="https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/140785214/ecfda096-36c2-43d8-9480-c21d0ba9cd1d">
사진 같이 올린다는거를 캡처만해놓고 올리질않았네요 죄송합니다

2024-05-17 11:33 UTC, snkchan approved these changes
@keeprok  고생하셨습니다. 수정사항 다 확인했어요~👍

2024-05-17 11:39 UTC, merged