PR : sign페이지에서 재사용되는 컴포넌트 모듈화를 통해 관심사분리했습니다.
mobi-projects/mobi-3rd-1-typescript pull request #123
Opened 2024-05-15 11:51 UTC by snkchan

## 🔥 Issues

- #122 

<br/>
<br/>

## 🎯 작업 내용

- [feat : LabeledInputWithError컴포넌트를 위한 함수 정의](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/89b3f4ddfba9f15cd37cc7625cff7c44fd92dc8e)
## 두가지 함수를 정의했습니다.🙌
- 1 문자열을 입력받아 첫글번째 글자만 대문자로 변환해서 반환해주는 capitalize() 를 생성했습니다.
```ts
ex)
 const word = email // => Email이라는 문자열이 필요하다면?
 const CapitallizedWord = capitalize({word:word}) // Email반환
```
- 2  isFieldError() 타입가드 함수를 정의했습니다.
```ts
<ErrorMsg errorField={errors[label]} >컴포넌트를 사용하기위해 errors[label가 FieldError타입인지 검사하기위해 정의
```

- [feat : 재사용 컴포넌트 LabeledInputWithError 생성](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/900517000fdd239398270ba6ef68f623b2656c27)
## 재사용컴포넌트 LabeledInputWithError 를 생성했습니다.
### 이전에는👇
기존 login,sign컴포넌트안에는 `<><Label/><Input/><ErrorMsg></>` 구조의 컴포넌트가 5개존재했습니다.
재사용가능한 컴포넌트를 생성해 하나의 컴포넌트로 관리하기위해 다음과 같이 작업했습니다.
### 현재는👇
- <Label/><Input/><ErrorMsg>세가지 컴포넌트를 포함한 공용컴포넌트인 LabeledInputWithError를 생성했습니다.
```ts
// login.tsx       
<form>                           //===> 수정후에는 다음과같이 보여지기때문에 컴포넌트 관리하기 더 수월할것 같아요
  <LabeledInputWithError/>
  <LabeledInputWithError/>
</form>
```
### 확인해야할부분👏
- ts로 공용컴포넌트를 만들다보니 아무래도 js공용컴포넌트보다 생성하기도 까다롭고 읽기도 좀어려울것 같아요 다음 내용들을 중점으로 봐주시면 좋을것 같습니다.
- 1 공용컴포넌트를 선언할땐 제네릭 `<T>`를 사용해서 컴포넌트를 호출하는 쪽에서 타입을 지정할 수 있도록 작업했습니다.
  - ts이기때문에 T가 any타입이 되면 안되겠죠?  그렇기때문에 `T extends 어떤타입` 형식으로 타입을 좁혀줬습니다.
  - form태그에 사용할것이기에 `useForm<P>`에 기본적으로 사용되는 P타입을 extends하도록 했습니다
 ```ts
 export const LabeledInputWithError = <T extends SignFormType> // 위에서언급한P가 이번작업에서는 SignFormType입니다.
 ```
- 2 ErrorMsg컴포넌트의 위치를 옮겼습니다.
  - ErrorMsg는 새로만들어진 LabeledInputWithError 에서만 사용될 것이기에 LabeledInputWithError 아래에 직접선언해줬어요.
```ts
// LabeledInputWithError .tsx
export const LabeledInputWithError =()=>{}  // 한파일에서 관리할수 있도록 위치를 옮겼습니다.
const ErrorMsg = ()=>{}
```  
- [feat : 컴포넌트화를 통한 관심사 분리](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/11874c5af7bcd55d02edc64ebcd4389751985e50)
- LabeledInputWithError 를 login,signup컴포넌트에 적용시켰습니다.

<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] Issue 번호 설정 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

-----

#### 🙏 꼭 리뷰 남겨주세요.!!
- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-05-15 14:18 UTC, TransparentDeveloper requested changes
고생하셨습니다. :)

2024-05-15 14:18 UTC, TransparentDeveloper commented on src/pages/sign/components/labeled-input-with-error.tsx
> +  const errorField = errors[label]
# Request Level

  - [x] "🚧 재고해주시길.."

# Description

오타인것 같습니다. `captalalizedLebel` => `captalalizedLabel`

2024-05-15 14:18 UTC, TransparentDeveloper commented on src/pages/sign/sign.type.ts
> +}
# Request Level

  - [x] "🚧 재고해주시길.."


# Description
### `<T extends object>`
- 제 생각에는 그냥 <T> 로 적어도 될 같은데,  object 로부터 확장한다는 전제가 꼭 필요한가요?

### `label: Path<T>`
- string 타입이면 안되나요??

2024-05-15 14:48 UTC, snkchan commented on src/pages/sign/sign.type.ts
> +}
- Q : 제 생각에는 그냥 로 적어도 될 같은데, object 로부터 확장한다는 전제가 꼭 필요한가요?
- A : 질문을 주셨는데 저도 처음에 객체형태면 괜찮지 않나? 라는 생각을 했습니다. 
```ts
export type LabeledInputWithErrorPT<T extends object> = {
  register: UseFormRegister<T>
  label: Path<T>
  errors: FieldErrors<T>
  inputProps?: ComponentProps<"input">
}
```
보시는 것처럼 T에의해 아래 props들또한 타입도 정의가되는데 
<img width="535" alt="image" src="https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/144839872/01748e42-689c-4286-8957-032f9e91887a">
여기서 보시면 저희가 두개의 로그인&회원가입 을위한 훅을 준비했고 그안에 보시면 `useForm<타입>`을 정의해서 사용해야합니다. 이에따라서 T는 `useForm<타입>`에들어가는 `타입`을 기본으로 해야하지 않을까요?

- Q : label: Path<T> string 타입이면 안되나요??
- A : 저도 처음에 string으로 선언을 했습니다. 
- <img width="569" alt="image" src="https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/144839872/8c9a6bc6-d155-4a5e-8e0f-5cd4414b06ee">
- 다음과 같은 에러를 발생시키고 아마도 이를 해결하려면 
위에 두가지의견주신대로 Object와 string선언하면 문제가 해결될거같은데  특정한목적을 가진 컴포넌트기에 
type을 목적에 맞게 좁혀주는 것이 맞지않을까요??

2024-05-16 03:02 UTC, TransparentDeveloper commented on src/pages/sign/sign.type.ts
> +}
1번 내용에 대해서 의미 전달이 제대로 되지 않은 것 같습니다.

질문의 요지는 " `LabeledInputWithErrorPT` 에서 사용할 타입은 object 로 확장한 타입이어야 한다" 를 꼭 명시할 필요가 있냐는 것입니다.

```ts
// 🧚 현재
export type LabeledInputWithErrorPT<T extends object> = {....}

// 🌀 제안
export type LabeledInputWithErrorPT<T> = {....}
```

2024-05-16 03:40 UTC, TransparentDeveloper commented on src/funcs/type-guard/index.ts
> +}
as 는 타입을 단언하기 위해 사용하는 것으로 알고 있어요.

에러는 피할 수 있지만 이렇게 쓰는게 좋은 방법은 아닐 것 같습니다. 

특히 "undifined 일 수도 있다." 이 부분이 상당히 걸리네요..

이렇게 중복되는 요소를 합쳐서 분리하는게 어렵다면, 굳이 그렇게 할 필요가 있을지,, 방향부터 다시 잡고 가는 건 어떨까요?

결국 핵심은 input 이고, 사용자 입력이 유효한지 판단하는게 해당 컴포넌트의 가장 중요한 역할 아닌가요??

에러를 출력하는 건 다른 컴포넌트의 역할로 미뤄도 되지 않나 싶습니다.

하나의 컴포넌트 안에서 여러 역할을 수행하기 위해, 처리할 게 많아지고 있어요..
에러 메시지에 대해선 props drilling 도 일어났구요.


차라리 중복이 조금 있더라도 👇 아래 처럼 하면 유지보수도 쉽지 않을까요?

```tsx
      <LabeledInput .... />
      <Error .... />

      <LabeledInput .... />
      <Error .... />
```

2024-05-16 04:04 UTC, snkchan commented on src/pages/sign/sign.type.ts
> +}
@TransparentDeveloper 헉 제가 질문의 요지를 제대로 이해하지못한채로 답변했네요.. 좋은 지적이네요👍
- 처음에 제네릭을 사용해서 공용컴포넌트를 만드는 과정에 임시로 Object로 선언했엇는데 수정하지않았습니다.

- <T extends object>가아닌 <T>로 선언하는 것이 당연히 맞을 것 같습니다. 
```ts
type LabeledInputWithErrorPT<T> = {  // <T>형태로 선언했을때
  register: UseFormRegister<T>  
  label: Path<T>
  errors: FieldErrors<T>
  inputProps?: ComponentProps<"input">
}
```
- <img width="894" alt="image" src="https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/144839872/aeb411dd-a6da-4ee6-a8e5-223a8c912908">
이에 따라서 다음과 같은문제가 발생하는데 그 이유는 register,label,errors모두` useForm<S>`   S타입에 의해서 영향을 받게 되기때문입니다. 따라서 <T extends SignFormType>으로 수정했습니다. 

- 좋은 지적감사합니다. 덕분에 제네릭 T와 extends에대해 좀더 알아볼 수 있는 시간이 된거같습니다👏🙌

2024-05-16 04:34 UTC, snkchan commented on src/funcs/type-guard/index.ts
> +}
- `차라리 중복이 조금 있더라도 👇 아래 처럼 하면 유지보수도 쉽지 않을까요?`의 질문에 대해서는 이렇게한이유에 대해 설명해야할 부분이있습니다.
### 원래 구조에서는
```ts
<div>         // 다음과 같은 구조였습니다. 이를 하나의 컴포넌트로 만들기위해서는  제일상단의 div태그가 필요합니다.
  <Label/>
  <Input/>
  <ErrorMsg/> 
</div>
```
### 요청주신대로만든다면?
```ts
constLabeledInputWithError = ()=>{
  <div>           // ==> 불필요한 div태그가 생성됩니다.
    <Label/>
    <Input/>
  </div>
}
```
이렇게 불필요한 태그를 생성하는것은 별로다 라는 판단하에 하나의 컴포넌트로 생성하게된것입니다.
- `특히 "undifined 일 수도 있다." 이 부분이 상당히 걸리네요..` 에대해서는 동감합니다.
- <img width="482" alt="image" src="https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/144839872/3993a01e-16f7-4208-ad72-ec1a3da53387">
- 보시는 것처럼 errorField에 에러가 발생하지않았을때는 undefiend가 오는것이 당연하기때문에 이부분은 어떻게 해결해야할지 잘모르겠습니다.. 좋은 의견있으신가요?

2024-05-16 06:48 UTC, TransparentDeveloper approved these changes
고생하셨습니다. :)

2024-05-16 06:49 UTC, merged