PR : 유저정보 조회 & 수정 기능구현
mobi-projects/mobi-3rd-1-typescript pull request #38
Opened 2024-05-05 16:48 UTC by snkchan

## 🔥 Issues

- #21 

<br/>
<br/>

## 🎯 작업 내용

- [feat : 공용컴포넌트 header(임시) components 폴더로 이동](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/83724f9d8b5101f1ec9a775a15b79259f365e851)
  - 임시공용header가 필요해서 `src>components>header`위치로 옮겼습니다. 
  - 나중에 layout폴더생성하면 그쪽으로 포함시킬 예정입니다. 폴더위치옮기고 적용했습니다.
- [feat : header에 home버튼 추가 & 로그아웃 로직 수정](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/0ead30e2424586095ebde46a68d4e72ace40c2b8)
  - home버튼이 없어서 home버튼 추가하고 클릭시 home으로 이동할버튼생성했습니다.
  - _지금은 클릭하면 로그인 페이지로 이동합니다._
  - <img width="494" alt="image" src="https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/144839872/29e070b7-3977-49d5-ad2c-b69e6facb181">

- [chore : query-key.ts에서 쿼리키 관리](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/a69c584138163fa84bce78ae9f4d9d2f1decf0a4)
  - `constants > query-key.ts` 에서 query-key관리하도록 파일생성했습니다. 전역적으로 사용할 키 추가하시면 됩니다.
- [chore : my페이지 사용 type정의](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/4eec4668bc695bd1c8796c9420f1fb695673baae)
  - my페이지에서 사용할 type들 분리했습니다. 재사용되는 타입이 많은데 아직 정리가 덜 된것 같습니다
- [feat : 유저 정보를 바꾸기위해 띄울 모달컴포넌트 생성](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/eefb344537634ffbe8cb8dbf5c1e2f56bf78c3de)
  - <img width="115" alt="image" src="https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/144839872/2a19c96d-9ac1-4ab5-8675-d9c09c7c0378">
  - 유저정보 수정 모달컴포넌트 생성했습니다. 아직 어떤 정보수정을 할지 몰라서 임시로 두가지 input만 배치해두었습니다.
  -  기능동작은 성공했고 후에 `resgister(key)` 만 수정해주면됩니다.
  -  default value, 빈값으로 제출시 로직 같은 부분은 아직 추가안된상태입니다. @notice에 작성해뒀습니다.

- [feat : 유저정보 패칭 & 유저정보 업데이트 함수정의](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/a63ca5a647b40eee7c48879190d685bf04281983)
  - api요청함수 두개로 나눠서 작성했습니다.
  - `단순 조회`를 위한 함수
  -  parameter로 수정하고싶은 `{key:value}` 추가시 수정하는 함수
- [feat : 사용자 정보 변경 함수들 hooks로 분리](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/761213b6f7bf4b174ff382f778b007e62ba75844)
  - hooks로 view에서 logic분리했습니다.
  - mutation요청 성공시 query키 재조회하도록 구현해서 바로 패칭하도록 설정했습니다.
- [feat : my페이지 유저정보 조회&변경 기능구현](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/59d778af31174486e68196ff617e8e85640d0a1d)
  - my 페이지에서 다음과 같이 보여지도록 구현했습니다.
  - 요청 성공시 
  - <img width="802" alt="image" src="https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/144839872/f933f44c-6746-43d6-8fe9-2935e17a8cf3">
  - 성공직후 패칭결과 
  - <img width="484" alt="image" src="https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/144839872/4c2a2d8e-dd94-44f3-8a02-903d3185acec">

![bandicam-2024-05-06-01-25-55-893](https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/144839872/9111f437-87fb-41c7-9ee7-f54d4d91bca5)

<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] Issue 번호 설정 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

-----

#### 🙏 꼭 리뷰 남겨주세요.!!
- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-05-05 17:55 UTC, snkchan commented
- @snkchan
[fix : 로그아웃함수 error시 return값 추가](https://github.com/mobi-projects/mobi-3rd-1-typescript/pull/38/commits/94aff316bf1f6ecae43a85aa74b4517bc2e71182)
- 추가수정하사항 있습니다.
- 로그아웃로직에 error발생시 return값이 없어서 콘솔에 에러발생했습니다. error발생때도 return값을 추가했습니다.

2024-05-06 03:45 UTC, TransparentDeveloper reviewed
# Request Level
  - [x] "✅ LGTM"

# Description
고생하셨습니다 :)

2024-05-06 03:45 UTC, TransparentDeveloper approved these changes

2024-05-06 09:11 UTC, TransparentDeveloper requested changes

2024-05-06 09:11 UTC, TransparentDeveloper commented on src/pages/my/my.type.ts
> +}
# Request Level

<!--
  - [x] "🚨 꼭 수정해주세요.!"
-->

  - [x] "🚧 재고해주시길.."

<!--
  - [x] "✅ LGTM"
-->

# Description
- `UserDataType` 은 my 페이지에 국한되지 않고, 전역적으로 사용될 것 같습니다.
- `src > types` 폴더 아래, 별도의 파일을 만들어서 관리하는 게 어떨까요?

2024-05-06 10:40 UTC, merged