PR :  로그인 & 회원가입 페이지 퍼블리싱
mobi-projects/mobi-3rd-1-typescript pull request #56
Opened 2024-05-07 19:53 UTC by snkchan

## 🔥 Issues

- #52 

<br/>
<br/>

## 🎯 작업 내용

- [chore : 개발기준사이즈 iphone-xr로등록](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/64fcc40bcacf7ace40091cfb0dd75f32ff6c5e9e)
  - 처음 계획대로 가장작은 app-size => web-size작업을 위해 `tailwind.config.ts`에서 다음과같이 사이즈를 정했습니다.
  - <img width="413" alt="image" src="https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/144839872/bf011fb2-7aef-4802-ad3a-6e3d72090e04">
  - 이를 가장 상위tag에서 사이즈를 다음과같이 설정하고 자식 태그들은 w-full로 적용해서 상위 태그의 사이즈에 영향을 받게 설계했습니다.
  - <img width="529" alt="image" src="https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/144839872/bd1df99e-630c-43ee-b88a-6c5c44a737b4">
  - 우선 가장작은사이즈로 작업을 마무리하고 후에 size를 추가해서 미리설정해둔 최상단 태그에 사이즈를 일괄적용하는 방향으로 진행하면 편할 것 같아서 지금처럼 설정해뒀는데 리뷰 부탁드립니다.
- [chore : 유저정보 nickName 만 사용하게 변경](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/d3cbe159f2dddd5bccf01ee53ffa1b4ca80dba3a)
  - 기존 유저data안에 정보가 `nickName , location`으로 설정되있던 것을 회의결과를 반영해서 `nickName`만사용하도록 수정했습니다.
## 이렇게 설계했습니다.
  - shadcn을 적용했기때문에 기존 `sign-in & sign-up`페이지를 하나의 페이지로 합쳐서 관리하는 것이 효율적이라고 판단했습니다.
  - 이에 따라서 기존 경로들을 하나의경로 `sign`이라는 경로로 합치고 폴더또한 두개의폴더를 `sign`폴더 하나로 합쳤습니다.
## 회의해야할 부분
- 여기서 문제점이 좀 생기는데 제가우선 작업해둔 내용은 하나의 폴더안에서 회원가입 & 로그인 `func,hook,type`을 한폴더아래 각자의 파일로 관리했습니다. 로직,타입,훅을 많이 선언해둔 상태라서 하나의 파일에서 관리하는것이 효율적일지 아니면 다시 두개의 파일로 나누는것이 효율적일지 판단이 서지 않아서 임의로 작업해뒀습니다. 참고해주세요~~!
## 작업내용
- [chore : PATH 경로 sign-in & sign-up 두개에서 sign하나로 병합](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/83cd2c985cfb495a79ddfdd71b9c6021efdc81cf)
  - 기존 두개의 폴더에서 관리하던것을 하나의 sign폴더로 합치고 각 관심사에 맞게 파일별로 분리했습니다.
- [chore : shadcn활용해서 Sign에서 로그인 회원가입 관리](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/f7ad50dd5a808f07d81be5a2a96768734e640c00)
  - <img width="494" alt="image" src="https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/144839872/a5af7929-51ec-44c8-8bc8-a3f22b74fdb4">
  - <img width="452" alt="image" src="https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/144839872/e201f726-ec77-466e-bef1-89f730f03c65">
  - shadcn 적용해서 ui 배치하고 기능도 각자 컴포넌트에 맞게 옮겼습니다.

- [feat : sign-in & sign-up hook,func,type 하나의 폴더에서 관리하도록 변경](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/e9c8858deb76008da4225e128e56ad1190af6b40)
- [chore : navi -> navigate변경](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/0a0e8c9e8d19377055fdadf879ff43b79ccf877c)
  - navigate와 navi 로 선언되어있어서 navigate로 통일시켯습니다.
- [feat : sign-header 생성](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/e7db34660f488a0b91e4b87112979018f7182013)
  - 로그인 회원가입에 맞는 텍스트를 가진 헤더영역을 생성했습니다.
- [feat : sign페이지생성](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/93ae3ef466b2acdfab9dc38fea339cf4689bd588)
  - 로그인시 ui
  - ![bandicam-2024-05-08-04-32-54-707](https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/144839872/693d4d0e-4d3d-42e2-90b4-e22feaabe4d7)

  - 회원가입시 ui
  - ![bandicam-2024-05-08-04-33-17-057](https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/144839872/ac65e289-c374-4cc7-8735-0372536ef9b2)
  - 회원가입 실패시 
  - ![bandicam-2024-05-08-04-33-50-924](https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/144839872/e8440e9b-b860-4b9d-a289-abd3290b7a32)

<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] Issue 번호 설정 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

-----

#### 🙏 꼭 리뷰 남겨주세요.!!
- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-05-07 20:04 UTC, snkchan commented
pr 올리고보니 
```ts
<div className = "IPHONE_XR: p-3">
// 아래처럼 적용하는것이 더좋아보이네요... 
<Tabs className = "IPHONE_XR: p-3">
```

2024-05-08 00:37 UTC, TransparentDeveloper requested changes
# Request Level

  - [x] "🚨 꼭 수정해주세요.!"


# Description
- pages 아래, `sign-in`, `sign-up` 폴더를 제거하고, `sign` 으로 통합한 건 아주 좋을 것 같습니다. 👍
- 그런데 `sign` 폴더 아래, `sign-in`, `sign-up` 다시 부활한 거는,,,ㅎㅎㅎ 이러면 굳이 나눌 이유가 없지 않았나 생각을 합니다. 
- 보니까 로그인 기능/ 회원가입 관련 "컴포넌트" 가 있는데, 전에 폴더 트리 정했던대로, 페이지를 구성하는 서브 컴포넌트는 `components` 폴더로 관리하지고 했었는데, 그것에 따르는게 어떨까요?

2024-05-08 00:37 UTC, TransparentDeveloper commented on src/constants/design-key.ts
> +export const D_SIGN_UP = "SignUP" as const
# Request Level
- [x] "✅ LGTM"

# Description
- 제가 shadcn 처음 써봐서 잘 모르겠는데, 이 key 의 용도는 무엇인가요?

2024-05-08 00:37 UTC, TransparentDeveloper commented on src/components/header/index.tsx
>        >
# Request Level


  - [x] "🚨 꼭 수정해주세요.!"



# Description
'async' 가 불필요한 것 같습니다.

2024-05-08 02:10 UTC, snkchan commented on src/constants/design-key.ts
> +export const D_SIGN_UP = "SignUP" as const
- Tabs컴포넌트를 사용할때 Tabtrigger와 TabContent컴포넌트를 동기화 시키는 목적으로 사용합니다.
```ts
// 사용이해를 위해 예시로 작성한것입니다. 실제는 구조가달라요~
<Tabs>
 <TabTrigger value="CaseA" >
   <TabContent value="CaseA"/>
 </TabTrigger >
 <TabTrigger value="CaseB">
  <TabContent value="CaseB" />
 </TabTrigger >
</Tabs>
```
만약 위와 같은구조라면 트리거가 CaseA가선택되면 그에맞는 컨텐트 가 화면에 보여지는 구조입니다~

2024-05-08 02:15 UTC, snkchan commented
- [chore : 불필요한 태그 제거](https://github.com/mobi-projects/mobi-3rd-1-typescript/pull/56/commits/581c8b940f5bf28e9440ddd4dea21cd382af1acb)
- 기존에 사이즈를 컨트롤하기위해 최상단에 <div>태그를 사용했었는데 
- [snkchan](https://github.com/snkchan) commented [6 hours ago](https://github.com/mobi-projects/mobi-3rd-1-typescript/pull/56#issuecomment-2099208832)
해당 코멘트에서 언급한 것처럼 Tabs에 적용하는것으로 수정완료했습니다!

2024-05-08 02:16 UTC, snkchan commented
- [chore : 페이지단위 사용될 자식컴포넌트들 components폴더에서 관리하도록 변경](https://github.com/mobi-projects/mobi-3rd-1-typescript/pull/56/commits/c36722a29e9efad948e42886401794b1fbfb5911)
- [TransparentDeveloper](https://github.com/TransparentDeveloper) requested changes [1 hour ago](https://github.com/mobi-projects/mobi-3rd-1-typescript/pull/56#pullrequestreview-2044416134)
의견주신대로 components폴더 생성해서 자식컴포넌트들 관리하도록 변경했습니다. 훨씬 관리하기 좋은것 같습니다.!

2024-05-08 03:47 UTC, merged