PR : 마이페이지 모달 디자인 변경 및 기능추가
mobi-projects/mobi-3rd-1-typescript pull request #66
Opened 2024-05-09 07:57 UTC by keeprok

## 🔥 Issues

- close #59

<br/>
<br/>

## 🎯 작업 내용

 -[[desing : 기존modal삭제후 Dialog모달 사용 및 디자인 변경](https://github.com/mobi-projects/mobi-3rd-1-typescript/commit/83093e7202aafc1985f6a632d473fc8660316a9a)

 - Dialog 의 구조를 가져가기로 해서 기존 modal myPage 모달 삭제 했습니다 
 - 기존 modal의 기능과 별개로 많은 여백부분은 디자인적으로 삭제 조치했습니다
 - 추가적으로 닉네임 수정시 모달바로닫는 DialogClose 기능 적용했습니다 
```ts
                <Input
                  className="border-2"
                  placeholder={data?.data.nickName || "닉네임입력좀"}
                  {...register("nickName")}
                />
              </div>
              <DialogClose>
                <Button
                  type="submit"
                  className="boreder-2 w-[10rem] rounded-full bg-blue-400 p-3 hover:bg-blue-50"
                  // disabled={!isValid} //스키마 정의 후 사용 예정
                >
                  Apply
                </Button>
              </DialogClose>
```
 - 추가적으로 페이지 이동없이 수정버튼을 두번이용시 dialog을 사용함에따라 input에 데이터가 남아있는 부부은 reset을 사용 했습니다 
```
 const { register, handleSubmit, reset } = useSubmitUpdateData()
  const onSubmitUpdateData = (data: UpdataDataType) => {
    nameMutate(data)
    reset()
  }
```
- 이전 닉네임을  placeholder 통해 걸어놨는데 더좋은 디자인있으면 변경하도록 하겠습니다 
     - 추가적으로 반응형시 사진입니다
<img width="346" alt="스크린샷 2024-05-09 오후 4 56 59" src="https://github.com/mobi-projects/mobi-3rd-1-typescript/assets/140785214/3aab2527-7ed5-408d-8d6b-67f00b24a4c5">

<br/>
<br/>

## ✅ 체크 리스트

-   [ ] Main 브랜치 Pull 받기
-   [ ] Issue 번호 설정 확인
-   [ ] Label 확인
-   [ ] Assignees 설정 확인
-   [ ] Reviewers 설정 확인

<br/>
<br/>

-----

#### 🙏 꼭 리뷰 남겨주세요.!!
- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-05-09 10:48 UTC, snkchan approved these changes
- 고생하셧습니다 해당pr에서 요구한것은 다마무리하신거 같아요 👍

2024-05-09 13:29 UTC, TransparentDeveloper requested changes
고생하셨습니다. 👍

2024-05-09 13:29 UTC, TransparentDeveloper commented on src/pages/my/index.tsx
> +      </Dialog>
# Request Level

<!--
  - [x] "🚨 꼭 수정해주세요.!"
-->

  - [x] "🚧 재고해주시길.."

<!--
  - [x] "✅ LGTM"
-->

# Description
- 관심사 분리가 필요해 보입니다. 
- dialog 태그와 my-page 로직이 강하게 연결되어 있어요.
- 다른 페이지에서 같은 dialog 디자인을 사용하려면 어떻게 해야하죠?
  - `components > dialog > index.tsx` 에  이 구성을 두고, import 해서 사용하는게 좋을 것 같습니다.
  - dialog 파라미터로 함수나 값을 전달하도록 하면, my-page 뷰가 더 돋보일 것 같습니다 :)

2024-05-09 13:29 UTC, TransparentDeveloper commented on src/pages/my/index.tsx
>          </p>
# Request Level

<!--
  - [x] "🚨 꼭 수정해주세요.!"
-->

<!--
  - [x] "🚧 재고해주시길.."
-->

  - [x] "✅ LGTM"

# Description
좋은 생각입니다.. 근데 이제 이런걸 코드 사이에 남기는 것보다 회의 때나 pr 로 전달하면 효과적일 것 같습니다. 😁

2024-05-09 18:06 UTC, keeprok commented on src/pages/my/index.tsx
>          </p>
아 pr에 적어둘것을 미리 작성한건데 수정을 안했네요 결론적으론 의견은 따로 제시 받아서 삭제 조치 하겠습니다

2024-05-10 15:55 UTC, keeprok commented on src/pages/my/index.tsx
> +      </Dialog>
[feat : modal 관심사분리 및 이전 modal 부분 삭](https://github.com/mobi-projects/mobi-3rd-1-typescript/pull/66/commits/adb6137b8545858e74c5a5e7ae7870833c2613cc) 해결했습니다 늦게 답변드려 죄송합니다

2024-05-11 03:32 UTC, TransparentDeveloper requested changes
고생하셨습니다~!

2024-05-11 03:32 UTC, TransparentDeveloper commented on src/components/dialog/dialog.type.ts
>  }
# Request Level

  - [x] "🚨 꼭 수정해주세요.!"

# Description
- 컴포넌트 프롭스 이름에 대한 컨벤션이 있습니다. 확인해주세요~

2024-05-11 03:32 UTC, TransparentDeveloper commented on src/components/dialog/dialog.type.ts
>  }
# Request Level


  - [x] "🚧 재고해주시길.."


# Description
-----
- form 은 제가 생각했을 때, 입력폼이 생각나는데 입력을 받기위한 모달인가요?
- 스크린샷 보니까 그런거 같은데, 꼭 그럴 용도로만 사용할 필요가 있을까요? 
- 더 다양한 컴포넌트를 포함할 수 있도록 children 사용하는게 좋지 않을까요?

----------
- `modalForm` , `modalBtn` 의 타입이 모두 ReactNode 로 설정하셨습니다. 
- `modalBtn` 버튼 컴포넌트를 외부 선언해서 넘겨주는 구조인가요?
- 그렇게도 쓸 수 있을 것 같긴한데, 디자인 통일성이 사라질 것 같아요.

근데 이거 어떻게 사용하는 건가요? 예시 코드 남겨주실 수 있나요??

2024-05-11 05:57 UTC, keeprok commented on src/components/dialog/dialog.type.ts
>  }
- form부분은 props로trigger와 form 의 연관성으로 trigger을 통해 form을 보여준다라는의미 로 다양한것을 의미할려고했지만
 - 모달의 속한 것을 표현하기위한 children이 변수를 직관적으로 알기 더쉬울것같습니다 좋은의견 감사합니다 수정하겠습니다 
 ---
- 추가수정 들어갔습니다  -modalForm , modalBtnd을  Children에 한번에 묶어서 보내는 식으로 작성했습니다 
```
   <form
      onSubmit={handleSubmit(onSubmitUpdateData)}
      className="flex h-[10rem]  flex-col items-center gap-3 "
    >
      <h3 className="py-5 font-bold">New Nick Name</h3>
      <div>
        <Input
          className="border-2"
          placeholder={data?.data.nickName || "닉네임입력좀"}
          {...register("nickName")}
        />
      </div>
      <DialogClose
        type="submit"
        className="boreder-2 w-[10rem] rounded-full bg-blue-400 p-3 hover:bg-blue-50"
      >
        적용
      </DialogClose>
    </form>
```
으로 잡앗습니다 
 또한 디자인 통일성 을 위해

```export const DialogModal: FC<DialogModalPT> = ({
  modalTrigger,
  children,
  isAlert = false,
}) => {
return( ...
{isAlert && (
            <DialogClose className="flex justify-center ">
              <div className="boreder-2 w-[10rem] rounded-full bg-blue-400 p-3 hover:bg-blue-50">
                확인
              </div>
            </DialogClose>
          )}
```
을 추가하여 isAlert를 기능적용이아닌 단순 확인용으로는 디자인 통일하여 넣어뒀습니다

2024-05-11 06:01 UTC, keeprok commented on src/components/dialog/dialog.type.ts
>  }
수정했습니다[Design : DialogModal baseButton 적용](https://github.com/mobi-projects/mobi-3rd-1-typescript/pull/66/commits/70e81c7643791d2cacdd2abc2596dfeff8c70255)

2024-05-11 06:21 UTC, TransparentDeveloper commented
고생하셨습니다.

일단 코드에 대한 리뷰하기 전에, 우리 커밋메시지 컨벤션 정한 것 중에 `design` 은 없습니다.
다시 한번 확인 부탁합니다.

@snkchan 
main 에 merge 된 것도 확인해보니, chan 님도 `design` 쓰셨네요..;;;

가끔 실수 할 수는 있어도, 최대한 신경써서 작업합시다.🔥!!!

2024-05-12 00:04 UTC, snkchan commented
> 고생하셨습니다.
> 
> 일단 코드에 대한 리뷰하기 전에, 우리 커밋메시지 컨벤션 정한 것 중에 `design` 은 없습니다. 다시 한번 확인 부탁합니다.
> 
> @snkchan main 에 merge 된 것도 확인해보니, chan 님도 `design` 쓰셨네요..;;;
> 
> 가끔 실수 할 수는 있어도, 최대한 신경써서 작업합시다.🔥!!!

허억.....제서합니다,,,

2024-05-12 08:26 UTC, closed without merging